services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${DB_USER}", "-db", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    command: ["-database", "postgres://admin:password@postgres:5432/db?sslmode=disable", "-path", "/migrations", "up"]
    volumes:
      - ./db/migrations:/migrations
    restart: no

volumes:
  postgres_data:
