services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports: 
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports: 
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

  

  migrate:
    image: migrate/migrate
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    command: ["-database", "postgres://admin:password@postgres:5432/db?sslmode=disable", "-path", "/migrations", "up"]
    volumes:
      - ./db/migrations:/migrations
    restart: no


  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped


  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: bank-jaeger
    ports:
      - "16686:16686" 
      - "4318:4318"  
    


volumes:
  postgres_data:
  redis_data:
    driver: local
  prometheus:
  grafana_data:
  jaegar_data:
